name: DevOps Learning CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code từ GitHub
      uses: actions/checkout@v4

    - name: Chạy câu lệnh kiểm tra user
      run: whoami

    - name: Chạy câu lệnh in ra màn hình
      run: echo "Hello từ GitHub Actions"
    - name: Triển khai lên Server qua SSH
      uses: appleboy/ssh-action@v1.0.3   # Action phổ biến để SSH vào server
      with:
       proxy_host: localhost
       host: ${{ secrets.SERVER_HOST }}      # Địa chỉ IP của server của bạn
       username: ${{ secrets.SERVER_USER }}  # Tên đăng nhập (ví dụ: ubuntu, root)
       key: ${{ secrets.SSH_PRIVATE_KEY }}   # Khóa SSH cá nhân để login không cần mật khẩu
       port: 443
       script: |
          cd /path/to/your/project            # Di chuyển vào thư mục dự án trên server
          git pull origin main                 # Kéo code mới nhất về
          # Thêm các lệnh khởi động lại ứng dụng của bạn ở đây, ví dụ:
          # npm install
          # pm2 restart all
